### Import lib

In [1]:
import torch
import torch.nn as nn

<div style="text-align:center;">
    <img src="../assets/transformer_explain.png" alt="decoder">
</div>

<!-- ![title](../assets/transformer.png) -->

<div style="text-align:center;">
    <img src="../assets/transformer.png" alt="decoder">
</div>

<div style="text-align:center;">
    <img src="../assets/mask.png" alt="decoder">
</div>

**Terminology**
- 'src_vocab_size': Kích thước từ vựng của ngôn ngữ nguồn (source).
- 'trg_vocab_size': Kích thước từ vựng của ngôn ngữ đích (target).
- 'src_pad_idx': Chỉ số của token PAD trong từ điển của ngôn ngữ nguồn.
- 'trg_pad_idx': Chỉ số của token PAD trong từ điển của ngôn ngữ đích.
- 'embed_size': Kích thước của vector nhúng (embedding) cho mỗi từ.
- 'num_layers': Số lượng các lớp trong mô hình.
- 'forward_expansion': Hệ số mở rộng cho lớp feed-forward trong các khối encoder và decoder.
- 'heads': Số lượng đầu ra (heads) trong tầng multi-head attention.
- 'dropout': Tỷ lệ dropout được áp dụng trong mô hình để tránh overfitting.
- 'device': Thiết bị sử dụng cho việc tính toán, ví dụ: "cuda" hoặc "cpu".
- 'max_length': Chiều dài tối đa của chuỗi đầu vào.

### 1. Self Attention

<!-- ![title](../assets/key-query-value.png) -->

<div style="text-align:center;">
    <img src="../assets/key-query-value.png" alt="decoder">
</div>

<!-- ![title](../assets/1_attention.png) -->

<div style="text-align:center;">
    <img src="../assets/1_attention.png" alt="decoder">
</div>

In [55]:
class SelfAttention(nn.Module):
    def __init__(self, embed_size, heads):
        super(SelfAttention, self).__init__()
        self.embed_size = embed_size
        self.heads = heads
        self.head_dim = embed_size // heads
        
        assert (self.head_dim * heads == embed_size),  "Embed size needs to be dive by heads"
        
        self.values = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.keys = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.queries = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.fc_out = nn.Linear(heads*self.head_dim, embed_size)
    
    def forward(self, values, keys, query, mask):
        N = query.shape[0]
        value_len, key_len, query_len = values.shape[1], keys.shape[1], query.shape[1]
        
        # Split embedding into self.head pieces
        values = values.reshape(N, value_len, self.heads, self.head_dim)
        keys = keys.reshape(N, key_len, self.heads, self.head_dim)
        queries = query.reshape(N, query_len, self.heads, self.head_dim)
        
        values = self.values(values)
        keys = self.keys(keys)
        queries = self.queries(queries)
        
        energy = torch.einsum("nqhd,nkhd->nhqk", [queries, keys]) # mantipulating matrix
        # queries shape: (N, query_len, heads, heads_dim)
        # keys shape: (N, key_len, heads, heads_dim)
        # enegy shape: (N, heads, query_len, key_len)
        # print(energy.shape)
        
        if mask is not None:
            energy = energy.masked_fill(mask==0, float("-1e20"))
        
        attention =  torch.softmax(energy / (self.embed_size**(1/2)), dim=3)
        
        out = torch.einsum("nhql,nlhd->nqhd", [attention, values]).reshape(
            N, query_len, self.heads*self.head_dim
        )
        # attention shape: (N, heads, query_len, key_len)
        # values shape: (N, value_len, heads, heads_dim)
        # after einsum (N, query_len, heads, head_dim) then flatten last two dimentions
            
        out = self.fc_out(out)
        return out
        

In [56]:
# Tạo một đối tượng SelfAttention
embed_size = 256
heads = 8
self_attention_layer = SelfAttention(embed_size, heads)

In [57]:
# Dummy input data
N = 10
value_len = 20
key_len = 20
query_len = 20
values = torch.randn(N, value_len, embed_size)
keys = torch.randn(N, key_len, embed_size)
queries = torch.randn(N, query_len, embed_size)
mask = None

# Forward pass
output = self_attention_layer(values, keys, queries, mask)
print("Output shape:", output.shape)

Output shape: torch.Size([10, 20, 256])


### 2. Transformer Block

<!-- ![title](../assets/transformer_block.png) -->

<div style="text-align:center;">
    <img src="../assets/transformer_block.png" alt="decoder">
</div>

In [58]:
class TransformerBlock(nn.Module):
    def __init__(self, embed_size, heads, dropout, forward_expansion):
        super(TransformerBlock, self).__init__()
        self.attention = SelfAttention(embed_size=embed_size, heads=heads)
        self.norm1 = nn.LayerNorm(embed_size)
        self.norm2 = nn.LayerNorm(embed_size)
        self.feed_forward = nn.Sequential(
            nn.Linear(embed_size, forward_expansion*embed_size),
            nn.ReLU(),
            nn.Linear(forward_expansion*embed_size, embed_size)
        )
        self.dropout = nn.Dropout(dropout)
    
    def forward(self, value, key, query, mask):
        attention = self.attention(value, key, query, mask)
        
        x = self.dropout(self.norm1(attention+query))
        forward = self.feed_forward(x)
        out = self.dropout(self.norm2(forward+x))
        return out
        

In [59]:
# Test the TransformerBlock class
embed_size = 256
heads = 8
dropout = 0.1
forward_expansion = 4

transformer_block = TransformerBlock(embed_size, heads, dropout, forward_expansion)

# Dummy input data
N = 10
value_len = 20
key_len = 20
query_len = 20
value = torch.randn(N, value_len, embed_size)
key = torch.randn(N, key_len, embed_size)
query = torch.randn(N, query_len, embed_size)
mask = None

# Forward pass
output = transformer_block(value, key, query, mask)
print("Output shape:", output.shape)

Output shape: torch.Size([10, 20, 256])


### 3. Encoder

<!-- ![encoder](../assets/encoder.png) -->

<div style="text-align:center;">
    <img src="../assets/encoder.png" alt="decoder">
</div>

In [60]:
class Encoder(nn.Module):
    def __init__(
        self,
        src_vocab_size,
        embed_size,
        num_layers,
        heads,
        device,
        forward_expansion,
        dropout,
        max_lenght,
    ):
        super(Encoder, self).__init__()
        self.embed_size = embed_size
        self.device = device
        self.word_embedding = nn.Embedding(src_vocab_size, embed_size)
        self.position_embedding = nn.Embedding(max_lenght, embed_size)
        
        self.layers = nn.ModuleList(
            [
                TransformerBlock(
                    embed_size,
                    heads,
                    dropout,
                    forward_expansion=forward_expansion,
                )
                for _ in range(num_layers)
            ]
        )
        self.dropout = nn.Dropout(dropout)
    
    def forward(self, x, mask):
        N, seq_lenght = x.shape
        positions = torch.arange(0, seq_lenght).expand(N, seq_lenght).to(self.device)
        
        out = self.dropout(self.word_embedding(x) + self.position_embedding(positions))
        
        for layer in self.layers:
            out = layer(out, out, out, mask)
        
        return out

In [61]:
# Test the Encoder class
src_vocab_size = 10000  # Replace with the actual vocabulary size
embed_size = 256
num_layers = 6
heads = 8
device = "cuda" if torch.cuda.is_available() else "cpu"
forward_expansion = 4
dropout = 0.1
max_length = 100  # Replace with the maximum sequence length

encoder = Encoder(
    src_vocab_size,
    embed_size,
    num_layers,
    heads,
    device,
    forward_expansion,
    dropout,
    max_length,
)

# Dummy input data
N = 10
seq_length = 20
x = torch.randint(0, src_vocab_size, (N, seq_length))
mask = None

# Forward pass
output = encoder(x, mask)
print("Output shape:", output.shape)

Output shape: torch.Size([10, 20, 256])


### 4. Decoder

<div style="text-align:center;">
    <img src="../assets/decoder.png" alt="decoder">
</div>


In [75]:
class DecoderBlock(nn.Module):
    def __init__(self, embed_size, heads, forward_expansion, dropout, device):
        super(DecoderBlock, self).__init__()
        self.norm = nn.LayerNorm(embed_size)
        self.attention = SelfAttention(embed_size, heads=heads)
        self.transformer_block = TransformerBlock(
            embed_size, heads, dropout, forward_expansion
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, value, key, src_mask, trg_mask):
        attention = self.attention(x, x, x, trg_mask)
        query = self.dropout(self.norm(attention + x))
        out = self.transformer_block(value, key, query, src_mask)
        return out


class Decoder(nn.Module):
    def __init__(
        self,
        trg_vocab_size,
        embed_size,
        num_layers,
        heads,
        forward_expansion,
        dropout,
        device,
        max_length,
    ):
        super(Decoder, self).__init__()
        self.device = device
        self.word_embedding = nn.Embedding(trg_vocab_size, embed_size)
        self.position_embedding = nn.Embedding(max_length, embed_size)

        self.layers = nn.ModuleList(
            [
                DecoderBlock(embed_size, heads, forward_expansion, dropout, device)
                for _ in range(num_layers)
            ]
        )
        self.fc_out = nn.Linear(embed_size, trg_vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_out, src_mask, trg_mask):
        N, seq_length = x.shape
        positions = torch.arange(0, seq_length).expand(N, seq_length).to(self.device)
        x = self.dropout((self.word_embedding(x) + self.position_embedding(positions)))

        for layer in self.layers:
            x = layer(x, enc_out, enc_out, src_mask, trg_mask)

        out = self.fc_out(x)

        return out

### 5. Transformer

<div style="text-align:center;">
    <img src="../assets/transformer1.png" alt="decoder">
</div>

In [86]:
class Transformer(nn.Module):
    def __init__(
        self,
        src_vocab_size,
        trg_vocab_size,
        src_pad_idx,
        trg_pad_idx,
        embed_size=512,
        num_layers=6,
        forward_expansion=4,
        heads=8,
        dropout=0,
        device="cpu",
        max_length=100,
    ):

        super(Transformer, self).__init__()

        self.encoder = Encoder(
            src_vocab_size,
            embed_size,
            num_layers,
            heads,
            device,
            forward_expansion,
            dropout,
            max_length,
        )

        self.decoder = Decoder(
            trg_vocab_size,
            embed_size,
            num_layers,
            heads,
            forward_expansion,
            dropout,
            device,
            max_length,
        )

        self.src_pad_idx = src_pad_idx
        self.trg_pad_idx = trg_pad_idx
        self.device = device

    def make_src_mask(self, src):
        src_mask = (src != self.src_pad_idx).unsqueeze(1).unsqueeze(2)
        # (N, 1, 1, src_len)
        return src_mask.to(self.device)

    def make_trg_mask(self, trg):
        N, trg_len = trg.shape
        trg_mask = torch.tril(torch.ones((trg_len, trg_len))).expand(
            N, 1, trg_len, trg_len
        )

        return trg_mask.to(self.device)

    def forward(self, src, trg):
        src_mask = self.make_src_mask(src)
        trg_mask = self.make_trg_mask(trg)
        enc_src = self.encoder(src, src_mask)
        out = self.decoder(trg, enc_src, src_mask, trg_mask)
        return out, src_mask, trg_mask, enc_src


### Run

In [87]:
device =  torch.device('cuda' if torch.cuda.is_available() else "cpu")

x =  torch.tensor([[1, 5, 6, 4, 3, 9, 5, 2, 0], [4, 5, 6, 8, 3, 9, 5, 2, 0]]).to(device)
trg = torch.tensor([[1,7,4,3,5,9,2,0], [1,5,6,2,4,7,6,2]])

src_pad_idx=0
trg_pad_idx=0
src_vocab_size = 10
trg_vocab_size = 10
model = Transformer(src_vocab_size, trg_vocab_size, src_pad_idx, trg_pad_idx).to(device)

out, src_mask, trg_mask, enc_src = model(x, trg[:, :-1])
print(out.shape)

torch.Size([2, 7, 10])


In [88]:
src_mask

tensor([[[[ True,  True,  True,  True,  True,  True,  True,  True, False]]],


        [[[ True,  True,  True,  True,  True,  True,  True,  True, False]]]])

In [89]:
trg_mask

tensor([[[[1., 0., 0., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1., 1., 1.]]],


        [[[1., 0., 0., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1., 1., 1.]]]])

In [91]:
enc_src.shape

torch.Size([2, 9, 512])

In [84]:
trg[:, :-1]

tensor([[1, 7, 4, 3, 5, 9, 2],
        [1, 5, 6, 2, 4, 7, 6]])

In [83]:
trg

tensor([[1, 7, 4, 3, 5, 9, 2, 0],
        [1, 5, 6, 2, 4, 7, 6, 2]])